#Edited by:
#- Roger
#- Anton

apiName: "IPSEN3"

assets:
  mappings:
    /assets: /
  overrides:
    /: ../workshop-client/public_html/

server:
  rootPath: /api/*
  adminContextPath: /admin

# Database settings
database:

  # the name of the JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: DropWizard

  # the password
  password: Groep6SWAG

  # the JDBC URL
  url: jdbc:mysql://145.97.16.190:3306/IPSEN3G6
