-- MySQL Script generated by MySQL Workbench
-- 01/18/16 17:12:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RoosterDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RoosterDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RoosterDB` DEFAULT CHARACTER SET utf8 ;
USE `RoosterDB` ;

-- -----------------------------------------------------
-- Table `RoosterDB`.`Bankrekening`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`Bankrekening` (
  `Iban` CHAR(18) NOT NULL,
  `TenNameVan` VARCHAR(60) NULL,
  PRIMARY KEY (`Iban`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`Telefoon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`Telefoon` (
  `TelefoonNummer` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TelefoonNummer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`Docent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`Docent` (
  `DocentNummer` INT NOT NULL,
  `Voornaam` VARCHAR(45) NOT NULL,
  `Tussenvoegsel` VARCHAR(45) NULL,
  `Achternaam` VARCHAR(45) NOT NULL,
  `Titel` VARCHAR(5) NULL,
  `Vooletters` VARCHAR(10) NOT NULL,
  `Iban` CHAR(18) NOT NULL,
  `TelefoonNummer` INT NOT NULL,
  PRIMARY KEY (`DocentNummer`),
  INDEX `Iban_idx` (`Iban` ASC),
  INDEX `TelefoonID_idx` (`TelefoonNummer` ASC),
  CONSTRAINT `Docent1`
    FOREIGN KEY (`Iban`)
    REFERENCES `RoosterDB`.`Bankrekening` (`Iban`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Docent2`
    FOREIGN KEY (`TelefoonNummer`)
    REFERENCES `RoosterDB`.`Telefoon` (`TelefoonNummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`Vak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`Vak` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `IBAN`
    FOREIGN KEY ()
    REFERENCES `RoosterDB`.`Bankrekening` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`DocentVak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`DocentVak` (
  `DocentNummer` INT NOT NULL,
  `VakID` INT NOT NULL,
  PRIMARY KEY (`DocentNummer`, `VakID`),
  INDEX `VakID_idx` (`VakID` ASC),
  CONSTRAINT `DocentVak1`
    FOREIGN KEY (`DocentNummer`)
    REFERENCES `RoosterDB`.`Docent` (`DocentNummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DocentVak2`
    FOREIGN KEY (`VakID`)
    REFERENCES `RoosterDB`.`Vak` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`Sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`Sector` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(45) NOT NULL,
  `AantalOpleidingen` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`Opleiding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`Opleiding` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(45) NOT NULL,
  `SectorID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Opleiding1_idx` (`SectorID` ASC),
  CONSTRAINT `Opleiding1`
    FOREIGN KEY (`SectorID`)
    REFERENCES `RoosterDB`.`Sector` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`DocentOpleiding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`DocentOpleiding` (
  `DocentNummer` INT NOT NULL,
  `OpleidingID` INT NOT NULL,
  PRIMARY KEY (`DocentNummer`, `OpleidingID`),
  INDEX `DocentOpleiding2_idx` (`OpleidingID` ASC),
  CONSTRAINT `DocentOpleiding1`
    FOREIGN KEY (`DocentNummer`)
    REFERENCES `RoosterDB`.`Docent` (`DocentNummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DocentOpleiding2`
    FOREIGN KEY (`OpleidingID`)
    REFERENCES `RoosterDB`.`Opleiding` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`DocentSector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`DocentSector` (
  `DocentNummer` INT NOT NULL,
  `SectorID` INT NOT NULL,
  PRIMARY KEY (`DocentNummer`, `SectorID`),
  INDEX `DocentSector_idx` (`SectorID` ASC),
  CONSTRAINT `DocentSector1`
    FOREIGN KEY (`DocentNummer`)
    REFERENCES `RoosterDB`.`Docent` (`DocentNummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DocentSector`
    FOREIGN KEY (`SectorID`)
    REFERENCES `RoosterDB`.`Sector` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`Lokaal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`Lokaal` (
  `LokaalNummer` VARCHAR(10) NOT NULL,
  `AantalPlaatsen` INT NOT NULL,
  PRIMARY KEY (`LokaalNummer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`Reservering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`Reservering` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `LokaalNummer` VARCHAR(10) NOT NULL,
  `Tijdsblok` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Reservering1_idx` (`LokaalNummer` ASC),
  CONSTRAINT `Reservering1`
    FOREIGN KEY (`LokaalNummer`)
    REFERENCES `RoosterDB`.`Lokaal` (`LokaalNummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`DocentReservering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`DocentReservering` (
  `DocentNummer` INT NOT NULL,
  `ReserveringID` INT NOT NULL,
  `Aanmaakdatum` DATETIME NOT NULL,
  PRIMARY KEY (`DocentNummer`, `ReserveringID`),
  INDEX `DocentReservering2_idx` (`ReserveringID` ASC),
  CONSTRAINT `DocentReservering1`
    FOREIGN KEY (`DocentNummer`)
    REFERENCES `RoosterDB`.`Docent` (`DocentNummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DocentReservering2`
    FOREIGN KEY (`ReserveringID`)
    REFERENCES `RoosterDB`.`Reservering` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`Hulpmiddel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`Hulpmiddel` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Omschrijving` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`Inventaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`Inventaris` (
  `LokaalNummer` VARCHAR(10) NOT NULL,
  `HulpmiddelID` INT NOT NULL,
  PRIMARY KEY (`LokaalNummer`, `HulpmiddelID`),
  INDEX `Inventaris2_idx` (`HulpmiddelID` ASC),
  CONSTRAINT `Inventaris1`
    FOREIGN KEY (`LokaalNummer`)
    REFERENCES `RoosterDB`.`Lokaal` (`LokaalNummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Inventaris2`
    FOREIGN KEY (`HulpmiddelID`)
    REFERENCES `RoosterDB`.`Hulpmiddel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`OpleidingVak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`OpleidingVak` (
  `OpleidingID` INT NOT NULL,
  `VakID` INT NOT NULL,
  PRIMARY KEY (`OpleidingID`, `VakID`),
  INDEX `OpleidingVak2_idx` (`VakID` ASC),
  CONSTRAINT `OpleidingVak1`
    FOREIGN KEY (`OpleidingID`)
    REFERENCES `RoosterDB`.`Opleiding` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OpleidingVak2`
    FOREIGN KEY (`VakID`)
    REFERENCES `RoosterDB`.`Vak` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`Student` (
  `StudentNummer` INT NOT NULL,
  `Voornaam` VARCHAR(45) NOT NULL,
  `Tussenvoegsel` VARCHAR(45) NULL,
  `Achternaam` VARCHAR(45) NOT NULL,
  `Voorletters` VARCHAR(45) NOT NULL,
  `Iban` CHAR(18) NOT NULL,
  `TelefoonNummer` INT NOT NULL,
  PRIMARY KEY (`StudentNummer`),
  INDEX `Student1_idx` (`Iban` ASC),
  INDEX `Student2_idx` (`TelefoonNummer` ASC),
  CONSTRAINT `Student1`
    FOREIGN KEY (`Iban`)
    REFERENCES `RoosterDB`.`Bankrekening` (`Iban`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Student2`
    FOREIGN KEY (`TelefoonNummer`)
    REFERENCES `RoosterDB`.`Telefoon` (`TelefoonNummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`StudentOpleiding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`StudentOpleiding` (
  `StudentNummer` INT NOT NULL,
  `OpleidingID` INT NOT NULL,
  PRIMARY KEY (`StudentNummer`, `OpleidingID`),
  INDEX `StudentOpleiding2_idx` (`OpleidingID` ASC),
  CONSTRAINT `StudentOpleiding1`
    FOREIGN KEY (`StudentNummer`)
    REFERENCES `RoosterDB`.`Student` (`StudentNummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StudentOpleiding2`
    FOREIGN KEY (`OpleidingID`)
    REFERENCES `RoosterDB`.`Opleiding` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`StudentReservering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`StudentReservering` (
  `StudentNummer` INT NOT NULL,
  `ReserveringID` INT NOT NULL,
  `Aanmaakdatum` DATETIME NOT NULL,
  PRIMARY KEY (`StudentNummer`, `ReserveringID`),
  INDEX `StudentReservering2_idx` (`ReserveringID` ASC),
  CONSTRAINT `StudentReservering1`
    FOREIGN KEY (`StudentNummer`)
    REFERENCES `RoosterDB`.`Student` (`StudentNummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StudentReservering2`
    FOREIGN KEY (`ReserveringID`)
    REFERENCES `RoosterDB`.`Reservering` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`StudentVak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`StudentVak` (
  `StudentNummer` INT NOT NULL,
  `VakID` INT NOT NULL,
  PRIMARY KEY (`StudentNummer`, `VakID`),
  INDEX `StudentVak2_idx` (`VakID` ASC),
  CONSTRAINT `StudentVak1`
    FOREIGN KEY (`StudentNummer`)
    REFERENCES `RoosterDB`.`Student` (`StudentNummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StudentVak2`
    FOREIGN KEY (`VakID`)
    REFERENCES `RoosterDB`.`Vak` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RoosterDB`.`VakReservering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoosterDB`.`VakReservering` (
  `VakID` INT NOT NULL,
  `ReserveringID` INT NOT NULL,
  `Aanmaakdatum` DATETIME NOT NULL,
  PRIMARY KEY (`VakID`, `ReserveringID`),
  INDEX `VakReservering2_idx` (`ReserveringID` ASC),
  CONSTRAINT `VakReservering1`
    FOREIGN KEY (`VakID`)
    REFERENCES `RoosterDB`.`Vak` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VakReservering2`
    FOREIGN KEY (`ReserveringID`)
    REFERENCES `RoosterDB`.`Reservering` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
